import type { DashboardId, Priority } from "./types";

export interface SeedTask {
  dashboardId: DashboardId;
  sectionId: string;
  sectionTitle: string;
  itemId: string;
  order: number;
  title: string;
  subtitle: string;
  how: string;
  priority: Priority;
  link: string | null;
  linkLabel: string | null;
  driveLink: string | null;
}

const AIRWAY_DRIVE_FILE = "https://docs.google.com/document/d/1nJW38iPF61bZcyFXTEujSw9ykYUHPx7RSAnNuTFF3xA/edit?usp=sharing";
const MARPE_F_DRIVE_FILE = "https://docs.google.com/document/d/1CRkVG50Q-968WvHHNkwjAWAxpaCGsY9Tf2wDLTYgYOg/edit?usp=sharing";
const MARPE_E_DRIVE_FILE = "https://docs.google.com/document/d/1cjI3GVjaf3hzvXS53L22oD6nr0mWHvAhK4Gddda09WM/edit?usp=sharing";

export const SEED_TASKS: SeedTask[] = [
  // ---------------- AIRWAY ----------------
  {
    dashboardId: "airway",
    sectionId: "identity",
    sectionTitle: "Make the identity and authority explicit",
    itemId: "f1",
    order: 1,
    priority: "P0",
    title: 'Add the explicit "airway-focused orthodontist" identity line',
    subtitle: "Paste the ready-to-use identity sentence right after the opening paragraph.",
    driveLink: AIRWAY_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Add this exact sentence right after the opening paragraph on the airway page:\n\n"Dr. Bar is a Board-Certified, airway-focused orthodontist, meaning every evaluation looks beyond straight teeth to how the jaw and airway are developing together."\n\nNothing to compose — this is the final wording, ready to paste in.`,
  },
  {
    dashboardId: "airway",
    sectionId: "identity",
    sectionTitle: "Make the identity and authority explicit",
    itemId: "f2",
    order: 2,
    priority: "P1",
    title: "Name the early-screening step",
    subtitle: 'Add the "Early Airway Check (Ages 6–7)" subheading and paragraph.',
    driveLink: AIRWAY_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Add this exact subheading and paragraph:\n\n"The Early Airway Check (Ages 6–7)\nAround age 6–7, Dr. Bar offers a focused evaluation of jaw growth and airway development, before permanent teeth fully come in, when guidance options are simplest. This isn't a diagnosis of sleep apnea; it's a screening to catch jaw or airway concerns early enough that less invasive treatment is usually possible."`,
  },
  {
    dashboardId: "airway",
    sectionId: "identity",
    sectionTitle: "Make the identity and authority explicit",
    itemId: "f3",
    order: 3,
    priority: "P1",
    title: "Cite the AAO white paper on OSA and orthodontics",
    subtitle: "Add the AAO citation sentence near the FAQ section.",
    driveLink: AIRWAY_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Add this exact sentence near the FAQ section:\n\n"The American Association of Orthodontists' white paper on obstructive sleep apnea notes that orthodontists play a role in airway-related care when working alongside a physician or sleep specialist, which is why Dr. Bar coordinates with ENTs and sleep doctors when a case calls for it."`,
  },
  {
    dashboardId: "airway",
    sectionId: "identity",
    sectionTitle: "Make the identity and authority explicit",
    itemId: "f4",
    order: 4,
    priority: "P0",
    title: "Link the ScoreApp quiz directly from this page",
    subtitle: "Add a callout box linking to the free 30-second quiz.",
    driveLink: AIRWAY_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Add this exact callout box after the "When to Consider" section, linking to https://drbarortho.scoreapp.com:\n\n"Not sure if this applies to your child? Take our free 30-second quiz: Does Your Child Need to See an Orthodontist? →"`,
  },
  {
    dashboardId: "airway",
    sectionId: "identity",
    sectionTitle: "Make the identity and authority explicit",
    itemId: "f5",
    order: 5,
    priority: "P2",
    title: "Add the new FAQ entry",
    subtitle: "Add the airway-vs-sleep-apnea Q&A to the existing FAQ block.",
    driveLink: AIRWAY_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Add this exact question and answer to the existing FAQ block:\n\nQ: "Is airway-focused orthodontics the same as treating sleep apnea?"\nA: "Not exactly. Airway-focused orthodontics looks at how jaw growth and structure affect breathing, and can be part of a broader plan. Diagnosing or treating sleep apnea itself is done by a physician or sleep specialist, and Dr. Bar coordinates with those providers when needed."`,
  },
  {
    dashboardId: "airway",
    sectionId: "identity",
    sectionTitle: "Make the identity and authority explicit",
    itemId: "f6",
    order: 6,
    priority: "P2",
    title: "Tell Google the page was updated",
    subtitle: "Request indexing in Search Console after the edits above go live.",
    driveLink: null,
    link: "https://search.google.com/search-console",
    linkLabel: "Search Console",
    how: `No content needed. Log into Google Search Console for drbarortho.com, paste in the airway page's URL, and click "Request Indexing" after the edits above go live.`,
  },
  {
    dashboardId: "airway",
    sectionId: "identity",
    sectionTitle: "Make the identity and authority explicit",
    itemId: "f7",
    order: 7,
    priority: "P2",
    title: "Tell Bing too",
    subtitle: "Same idea in Bing Webmaster Tools.",
    driveLink: null,
    link: "https://www.bing.com/webmasters",
    linkLabel: "Bing tools",
    how: `No content needed. Same idea in Bing Webmaster Tools (verify the site there first if you haven't already).`,
  },
  {
    dashboardId: "airway",
    sectionId: "publish",
    sectionTitle: "Publish content AI can quote",
    itemId: "g1",
    order: 8,
    priority: "P1",
    title: 'Publish "Signs Your Child\'s Breathing May Affect Jaw Growth"',
    subtitle: "Fully written blog post — copy in and publish as-is.",
    driveLink: "https://docs.google.com/document/d/1z4NW1vrJEYRreC5fkUr7nouNKrefHPl8fAUO02Yq9J4/edit?usp=sharing",
    link: null,
    linkLabel: null,
    how: `This entire blog post is already written, start to finish. It's a separate attached file alongside this dashboard (titled about Signs Your Child's Breathing). Copy it exactly as written into a new blog post on drbarortho.com and publish. There is nothing left to write for this task.`,
  },
  {
    dashboardId: "airway",
    sectionId: "watch",
    sectionTitle: "Watch the competitive field",
    itemId: "w1",
    order: 9,
    priority: "P2",
    title: "Check Smiles ON's airway page quarterly",
    subtitle: "They currently have the strongest identity claim in the field.",
    driveLink: null,
    link: "https://smilesonorthodontics.com/katy-tx/airway-orthodontics/",
    linkLabel: "View their page",
    how: `No content involved. Every few months, open their page and skim it for new claims, since they currently have the strongest identity claim in the field.`,
  },
  {
    dashboardId: "airway",
    sectionId: "watch",
    sectionTitle: "Watch the competitive field",
    itemId: "w2",
    order: 10,
    priority: "P2",
    title: 'Check Katy Park\'s "Growth-Oriented Orthodontics" program page',
    subtitle: "Keep Dr. Bar's newly named program differentiated.",
    driveLink: null,
    link: "https://katyparkorthodontics.com/airway-orthodontics/",
    linkLabel: "View their page",
    how: `No content involved. Watch how they market their named early-intervention program every so often, so Dr. Bar's newly named program stays differentiated.`,
  },
  {
    dashboardId: "airway",
    sectionId: "track",
    sectionTitle: "Track progress",
    itemId: "m1",
    order: 11,
    priority: "P2",
    title: "Starting point recorded",
    subtitle: "Informational — starting measurement saved Sep 1, 2026.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `This just confirms a starting measurement was saved on Sep 1, 2026, so future checks have something to compare against. No action needed, this box is informational.`,
  },
  {
    dashboardId: "airway",
    sectionId: "track",
    sectionTitle: "Track progress",
    itemId: "m2",
    order: 12,
    priority: "P2",
    title: "Check progress once a month",
    subtitle: "Use the same buyer question and note if Dr. Bar is still named first.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `No content involved. Once a month, click the check buttons in the panel on the right using the same buyer question, and note whether Dr. Bar is still named first.`,
  },

  // ---------------- MARPE ----------------
  {
    dashboardId: "marpe",
    sectionId: "fix-first",
    sectionTitle: "Fix these first",
    itemId: "b2",
    order: 1,
    priority: "P2",
    title: "Map pin and address — already checked, no action needed",
    subtitle: "Verified: address correct, 5.0 stars, 49 reviews.",
    driveLink: null,
    link: "https://www.drbarortho.com/contact-us/",
    linkLabel: "View contact page",
    how: `We checked this live with Google: the address is correct (6850 Katy-Gaston Rd, Katy, TX 77494) and reviews are strong (5.0 stars, 49 reviews). This task is only here as a record that it was checked. Just tick the box.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "fix-first",
    sectionTitle: "Fix these first",
    itemId: "b3",
    order: 2,
    priority: "P0",
    title: "Dr. Bar reads and approves the new wording",
    subtitle: "Review the wording below before it's sent to Hatim.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `No content of its own. Have Dr. Bar review the wording in the tasks below before it's sent to Hatim, since AI tools and patients will quote it directly once it's live.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "quotable-page",
    sectionTitle: "Build the quotable page",
    itemId: "f1",
    order: 3,
    priority: "P0",
    title: 'Add opening paragraph leading with "palate expander for adults"',
    subtitle: "Replace the current opening sentence in the MARPE section.",
    driveLink: MARPE_F_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Replace the current opening sentence in the MARPE section with this exact paragraph:\n\n"A palate expander for adults — sometimes called MARPE (miniscrew-assisted rapid palatal expansion) — widens a narrow upper jaw without surgery, even after normal jaw growth has finished. Dr. Bar builds a custom 3D-printed MARPE appliance for each patient, anchored with mini-implants instead of relying on the teeth alone. Dr. Bar has helped adult patients up to around 52 years old with this approach, most often for crossbites, crowding, or breathing-related concerns where a traditional expander isn't an option."`,
  },
  {
    dashboardId: "marpe",
    sectionId: "quotable-page",
    sectionTitle: "Build the quotable page",
    itemId: "f2",
    order: 4,
    priority: "P0",
    title: "Add three new FAQ answers",
    subtitle: "Growth, terminology, and surgery Q&As for the FAQ block.",
    driveLink: MARPE_F_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Add these 3 exact Q&As to the existing FAQ block:\n\nQ: "Can I get a palate expander as an adult, or is it too late once I'm done growing?"\nA: "Yes. Traditional expanders work best in children because they rely on a growth plate that's still open. MARPE is built for adults and older teens whose jaw growth is complete, it uses mini-implants to apply the expansion force directly to the bone instead of the teeth, which is why it can still work after growth has finished."\n\nQ: "Is a palate expander for adults the same thing as MARPE?"\nA: "Yes, palate expander for adults is simply the plain-language way most people describe MARPE. Dr. Bar uses a custom 3D-printed MARPE appliance for adult cases."\n\nQ: "Do I need surgery for adult palate expansion?"\nA: "Not necessarily. MARPE is designed as a non-surgical option for many adults with a narrow or crowded jaw. Whether it's right for you depends on your CBCT scan and your individual case."\n\nAlso attached as a file for easy copy-paste: MARPE-Page-FAQs-and-Schema-Code.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "quotable-page",
    sectionTitle: "Build the quotable page",
    itemId: "f3",
    order: 5,
    priority: "P1",
    title: "Add the hidden label that AI reads (schema code)",
    subtitle: "Ready-to-paste schema code for the page head or SEO plugin.",
    driveLink: MARPE_F_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `This is ready-to-paste code, already written in full. It's in the attached file "MARPE-Page-FAQs-and-Schema-Code," in the section below the FAQs. Hatim pastes it into the page's page head or the SEO plugin's custom schema field, exactly as written, straight quotes only. This is not something anyone needs to compose.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "quotable-page",
    sectionTitle: "Build the quotable page",
    itemId: "f4",
    order: 6,
    priority: "P1",
    title: "Add byline and updated date stamp",
    subtitle: "Add the reviewed-by line near the top of the MARPE section.",
    driveLink: MARPE_F_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Add this exact line near the top of the MARPE section:\n\n"Reviewed by Dr. Bar Nguyen, DDS, MS — Board-Certified Diplomate, American Board of Orthodontics. Updated September 2026."`,
  },
  {
    dashboardId: "marpe",
    sectionId: "quotable-page",
    sectionTitle: "Build the quotable page",
    itemId: "f5",
    order: 7,
    priority: "P1",
    title: "Tell Google the page exists",
    subtitle: "Request indexing in Search Console.",
    driveLink: null,
    link: "https://search.google.com/search-console",
    linkLabel: "Search Console",
    how: `No content needed. Log into Google Search Console, paste in the page URL, click "Request Indexing."`,
  },
  {
    dashboardId: "marpe",
    sectionId: "quotable-page",
    sectionTitle: "Build the quotable page",
    itemId: "f6",
    order: 8,
    priority: "P1",
    title: "Tell Bing too",
    subtitle: "Same idea in Bing Webmaster Tools.",
    driveLink: null,
    link: "https://www.bing.com/webmasters",
    linkLabel: "Bing tools",
    how: `No content needed. Same idea in Bing Webmaster Tools.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "quotable-page",
    sectionTitle: "Build the quotable page",
    itemId: "f7",
    order: 9,
    priority: "P2",
    title: "Check your site welcomes AI crawlers",
    subtitle: "Confirm robots.txt allows GPTBot, ClaudeBot, PerplexityBot; check for llms.txt.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `No content to write. Ask your web developer to confirm robots.txt allows GPTBot, ClaudeBot, and PerplexityBot, and whether an llms.txt file exists. Couldn't be checked automatically this run.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "quotable-page",
    sectionTitle: "Build the quotable page",
    itemId: "f8",
    order: 10,
    priority: "P2",
    title: "Link this page from more places on the site",
    subtitle: "Add natural links from the homepage, LightForce, and Phase 1 pages.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `There's no fixed sentence here. It just means adding a natural link to this page from the homepage and from the LightForce and Phase 1 pages, something like mentioning "our airway-focused approach" with a link works fine. Use your judgment on the exact phrasing.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "ai-lists",
    sectionTitle: "Get onto the lists AI quotes",
    itemId: "c1",
    order: 11,
    priority: "P0",
    title: "Get listed on GetExpanded",
    subtitle: "Submit a provider profile with the ready-to-paste description.",
    driveLink: "https://docs.google.com/document/d/1Vqc-EPiekOIbxq2OeN0cJoeNpCWG0_RrHeVMMb6ts70/edit?usp=sharing",
    link: null,
    linkLabel: null,
    how: `Create a free account at getexpanded.org, click "Submit Provider," and enter:\n\nPractice: Dr. Bar Orthodontics\nProvider: Dr. Bar Nguyen, DDS, MS\nLocation: Katy, TX\nWebsite: drbarortho.com\nDevice: MARPE\n\nDescription (paste exactly): "Dr. Bar Orthodontics offers custom 3D-printed MARPE (miniscrew-assisted rapid palatal expansion) for adult and teen patients in Katy, TX, as part of an airway-focused approach to orthodontics. Dr. Bar has helped adult patients up to around age 52 with this non-surgical option for crossbites, crowding, and breathing-related concerns."`,
  },
  {
    dashboardId: "marpe",
    sectionId: "ai-lists",
    sectionTitle: "Get onto the lists AI quotes",
    itemId: "c2",
    order: 12,
    priority: "P2",
    title: "Check or create a Zocdoc profile",
    subtitle: "Confirm a claimed profile exists with matching info.",
    driveLink: null,
    link: "https://www.zocdoc.com/",
    linkLabel: "Open Zocdoc",
    how: `No content needed yet. Confirm whether Dr. Bar has a claimed Zocdoc profile with matching name, address, and specialties. If not, set one up, that part will need its own description written later.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "ai-lists",
    sectionTitle: "Get onto the lists AI quotes",
    itemId: "c3",
    order: 13,
    priority: "P2",
    title: "Correct the Healthgrades listing",
    subtitle: "Update the address to match the Katy location exactly.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `No content needed. Log in to Healthgrades' provider tools and update the address to match the Katy location exactly.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "ai-lists",
    sectionTitle: "Get onto the lists AI quotes",
    itemId: "c4",
    order: 14,
    priority: "P2",
    title: "Correct the WebMD listing",
    subtitle: "Same address fix, on WebMD's provider tools.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `No content needed. Same fix, on WebMD's provider tools.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "ai-lists",
    sectionTitle: "Get onto the lists AI quotes",
    itemId: "c5",
    order: 15,
    priority: "P1",
    title: "Check or claim a Yelp profile",
    subtitle: "Competitors rank in Yelp's Best Orthodontists in Katy list; Dr. Bar doesn't yet.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `Dr. Bar Orthodontics doesn't currently appear in Yelp's own "Best Orthodontists in Katy" rankings, while several direct competitors do (Katy Orthodontics, Hanis, Forrest, Blackburn & Williams). Check whether a Yelp profile exists and is claimed. If not, claim or create one with the standard entity description.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "ai-lists",
    sectionTitle: "Get onto the lists AI quotes",
    itemId: "c6",
    order: 16,
    priority: "P0",
    title: "Check Best of Katy 2026 voting status",
    subtitle: "Currently 2nd place behind Gavri Orthodontics — check if voting is still open.",
    driveLink: null,
    link: "https://www.bestofkaty.org/category/11682/health-and-wellness/best-orthodontist-practice",
    linkLabel: "View standings",
    how: `As of the last check, Dr. Bar Orthodontics is in 2nd place for "Best Orthodontist Practice," behind Gavri Orthodontics in 1st. Check whether voting is still open, and if so, consider a quick patient-facing push (email, Instagram) asking for votes.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "bio",
    sectionTitle: "Make the bio identical everywhere",
    itemId: "e1",
    order: 17,
    priority: "P1",
    title: "Update the Google Business Profile description",
    subtitle: "Paste the standard practice description word for word.",
    driveLink: MARPE_E_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Paste this exact paragraph into your Google Business Profile description, word for word:\n\n"Dr. Bar Orthodontics is a Board-Certified orthodontic practice in Katy, TX, led by Dr. Bar Nguyen, DDS, MS, offering airway-focused orthodontics, LightForce 3D custom braces, and custom 3D-printed MARPE for adult and teen patients."`,
  },
  {
    dashboardId: "marpe",
    sectionId: "bio",
    sectionTitle: "Make the bio identical everywhere",
    itemId: "e2",
    order: 18,
    priority: "P2",
    title: "Update the Instagram bio",
    subtitle: "Use the exact same paragraph from the Google Business Profile task.",
    driveLink: MARPE_E_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Use the exact same paragraph from the Google Business Profile task in the Instagram bio.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "bio",
    sectionTitle: "Make the bio identical everywhere",
    itemId: "e3",
    order: 19,
    priority: "P2",
    title: "Update the TikTok bio",
    subtitle: "Use the exact same paragraph from the Google Business Profile task.",
    driveLink: MARPE_E_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Use the exact same paragraph from the Google Business Profile task in the TikTok bio.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "bio",
    sectionTitle: "Make the bio identical everywhere",
    itemId: "e4",
    order: 20,
    priority: "P2",
    title: "Update the Facebook page description",
    subtitle: "Use the exact same paragraph from the Google Business Profile task.",
    driveLink: MARPE_E_DRIVE_FILE,
    link: null,
    linkLabel: null,
    how: `Use the exact same paragraph from the Google Business Profile task in the Facebook About section.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "publish",
    sectionTitle: "Publish content AI can quote",
    itemId: "g1",
    order: 21,
    priority: "P1",
    title: "Publish the honest listicle",
    subtitle: "Fully written, competitors included — copy in and publish.",
    driveLink: "https://docs.google.com/document/d/1KSVUQn69f92JokgApcljEAYtc9DnkHWoxKMZqtDEXvo/edit?usp=sharing",
    link: null,
    linkLabel: null,
    how: `This entire blog post ("Palate Expanders for Adults Near Katy & Houston") is already written, start to finish, competitors included and Dr. Bar clearly marked. It's a separate attached file. Copy it in and publish, nothing left to write.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "publish",
    sectionTitle: "Publish content AI can quote",
    itemId: "g2",
    order: 22,
    priority: "P2",
    title: "Publish the three short Q&A posts",
    subtitle: "Fully written — copy each in and publish.",
    driveLink: "https://docs.google.com/document/d/1ykh_l0mv7UC9is5acLapTnA3zJQ-ZH6DMUYoabA6ENo/edit?usp=sharing",
    link: null,
    linkLabel: null,
    how: `All three short Q&A posts are already written in full. They're in a separate attached file. Copy each in and publish, nothing left to write.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "publish",
    sectionTitle: "Publish content AI can quote",
    itemId: "g3",
    order: 23,
    priority: "P1",
    title: "Turn your real adult outcomes into a fact sheet",
    subtitle: "One-page fact sheet with real verified numbers — publish or share as-is.",
    driveLink: "https://docs.google.com/document/d/15bOqO5sTU-e75o0zX5s9ATx_WeP5ZHHWCukwsqK6JRA/edit?usp=sharing",
    link: null,
    linkLabel: null,
    how: `This one-page fact sheet is already written, with your real verified numbers (age range up to ~52, timeline, non-surgical). It's a separate attached file (MARPE-Fact-Sheet). Nothing left to write, just publish or share it as-is.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "share",
    sectionTitle: "Share it where AI looks",
    itemId: "d1",
    order: 24,
    priority: "P2",
    title: "Post a YouTube clip on adult palate expansion",
    subtitle: "Future content batch idea — not holding up current progress.",
    driveLink: null,
    link: "https://www.youtube.com/channel/UCjBM_8nsT4inepTjlG46WRA",
    linkLabel: "Open YouTube",
    how: `No script exists for this yet. It's an idea for a future content batch: a 60–90 second clip titled around "can adults get a palate expander?" on your existing channel. Not something holding up current progress.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "share",
    sectionTitle: "Share it where AI looks",
    itemId: "d2",
    order: 25,
    priority: "P2",
    title: "Answer a genuine question on Reddit",
    subtitle: "Answer helpfully when a real r/orthodontics or r/Invisalign thread comes up.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `No content to prepare in advance. When you come across a real r/orthodontics or r/Invisalign thread about adult MARPE, answer helpfully and mention Dr. Bar naturally.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "share",
    sectionTitle: "Share it where AI looks",
    itemId: "d3",
    order: 26,
    priority: "P2",
    title: "Share a myth-vs-fact Instagram post",
    subtitle: "Future content batch idea — not urgent.",
    driveLink: null,
    link: "https://www.instagram.com/drbarorthodontics",
    linkLabel: "Open Instagram",
    how: `No post exists for this yet. It's an idea for a future content batch: a short "myth: you can't expand your jaw as an adult" graphic or reel. Not urgent.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "track",
    sectionTitle: "Track progress",
    itemId: "m1",
    order: 27,
    priority: "P2",
    title: "Starting point recorded",
    subtitle: "Informational — starting measurement saved Sep 1, 2026.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `This just confirms a starting measurement was saved on Sep 1, 2026. No action needed, this box is informational.`,
  },
  {
    dashboardId: "marpe",
    sectionId: "track",
    sectionTitle: "Track progress",
    itemId: "m2",
    order: 28,
    priority: "P2",
    title: "Check progress once a month",
    subtitle: "Use the same buyer question in the panel on the right.",
    driveLink: null,
    link: null,
    linkLabel: null,
    how: `No content involved. Once a month, click the check buttons in the panel on the right using the same buyer question.`,
  },
];

export const SECTION_ORDER: Record<DashboardId, { id: string; title: string }[]> = {
  airway: [
    { id: "identity", title: "Make the identity and authority explicit" },
    { id: "publish", title: "Publish content AI can quote" },
    { id: "watch", title: "Watch the competitive field" },
    { id: "track", title: "Track progress" },
  ],
  marpe: [
    { id: "fix-first", title: "Fix these first" },
    { id: "quotable-page", title: "Build the quotable page" },
    { id: "ai-lists", title: "Get onto the lists AI quotes" },
    { id: "bio", title: "Make the bio identical everywhere" },
    { id: "publish", title: "Publish content AI can quote" },
    { id: "share", title: "Share it where AI looks" },
    { id: "track", title: "Track progress" },
  ],
};
